name: Parse Piped

on:
  schedule: 
    - cron: '00 10 */7 * *'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install httpx
      run: |
        python -m pip install httpx
    - name: Run piped main
      run: python piped/main.py
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'piped/*'
        message: 'AutoUpdate Piped list'
        default_author: github_actions
        push: true
